### DISCUSSION TITLE
'able' command line tool

### DISCUSSION THREAD

**Discussion by sanity** [freenet/freenet-core#412] [General]
Locutus' ability to support a wide variety of tools and languages for developing decentralized apps is both a blessing and a curse. The blessing is flexibility but the curse is developer convenience.

To address this, I've been working on a command line tool called `abel` that's designed to make it easy to create decentralized apps while mixing and matching various development tools and languages.

Current workflow is:

```
$ cargo install freenet-able
$ able create flood_tokens
$ cd flood_tokens
$ ls
able.toml
```

The able.toml file is used to set up the project, an example would be:

```toml
name="flood-tokens"

[flatbuffer-schemas]
type="directory"

[contracts.allocations]
type="rust-contract"

[components.token-generator]
type="rust-component"

[interface.typescript]
type="typescript-library"
```

The `apply` command is similar to the apply command in terraform, it synchronizes directory state with what's been decoratively specified in the `able.toml` file.

```
$ able apply
Create flatbuffer-schemas directory? [Y/N/A] Y
Create contracts.allocations rust-contract? [Y/N/A] Y
Create components.token-generator rust-component? [Y/N/A] Y
Create interface.typescript typescript-library? [Y/N/A] Y
$ 
```

Each subdirectory will be generated from a template based on the type, creating something like this directory structure:

```
[floodtokens
├── able.toml
├── contracts
│  └── allocations
│     └── able.toml
├── flatbuffer-schemas
└── interface
   └── typescript
      └── able.toml
```
