### ISSUE TITLE
Publish Freenet versions with Github Actions

### ISSUE THREAD

**Issue by sanity** [freenet/freenet-core#1548]
### Problem

Right now, publishing a crate involves tagging and pushing manually. This opens us up to the risk of accidentally tagging broken code or pushing a tag without realizing CI has failed. Since crates.io **doesn't allow re-publishing the same version**, this can cause permanent version lockouts.

### Goals

We want a CI workflow that:
- Publishes only if tests pass
- Verifies the git tag matches `Cargo.toml`
- Skips publishing if the version is already on crates.io
- Keeps everything GitHub Actions-based
- Makes recovery easy if a tag is pushed accidentally

---

### 🛠 Proposed Solution

Add the following GitHub Actions workflow under `.github/workflows/publish.yml`:

<details>
<summary>Click to expand</summary>

```yaml
name: Safe Crate Publish

on:
  push:
    tags:
      - "v*"

jobs:
  validate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: echo "version=$(grep '^version' Cargo.toml | head -1 | cut -d '\"' -f2)" >> "$GITHUB_OUTPUT"

      - name: Extract version from tag
        id: tag_version
        run: echo "version=${GITHUB_REF##refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Ensure tag matches Cargo.toml version
        run: |
          if [ "${{ steps.cargo_version.outputs.version }}" != "${{ steps.tag_version.outputs.version }}" ]; then
            echo "Version mismatch! Tag says v${{ steps.tag_version.outputs.version }}, but Cargo.toml has ${{ steps.cargo_version.outputs.version }}"
            exit 1
          fi

      - name: Run tests
        run: cargo test --locked

      - name: Check if version already published
        id: already_published
        run: |
          version="${{ steps.cargo_version.outputs.version }}"
          crate_name=$(basename "$(pwd)")
          curl -sSf https://crates.io/api/v1/crates/$crate_name/$version > /dev/null && echo "published=true" >> "$GITHUB_OUTPUT" || echo "published=false" >> "$GITHUB_OUTPUT"

      - name: Publish to crates.io
        if: steps.already_published.outputs.published == 'false'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --locked
```

</details>

---

### 🔁 Recovery Workflow

If a tag is pushed with failing code, **no crate is published**. Just fix the bug and:

```bash
git tag -d v1.2.3
git push origin :refs/tags/v1.2.3
git tag v1.2.3
git push --tags
```

CI will re-run and succeed the second time.

---

### ✅ Benefits

- Ensures tests pass before any publish attempt
- Prevents crates.io version lockout mistakes
- Keeps versioning discipline (`Cargo.toml` ↔ `git tag`)
- 100% GitHub Actions—no local scripts or manual publish steps
